import './models/category.dart';

const CATEGORIES = [
  Category(id: 'c1',title: 'Soap'),
  Category(id: 'c2',title: 'Toothpaste'),
  Category(id: 'c3',title: 'Shampoo'),
  Category(id: 'c4',title: 'Face Wash'),
  Category(id: 'c5',title: 'Personal Care'),
  Category(id: 'c6',title: 'Hair Oil'),
  Category(id: 'c7',title: 'Detergent'),
  Category(id: 'c8',title: 'Shaving Products'),
  Category(id: 'c9',title: 'Deo'),
  Category(id: 'c10',title: 'Face Powder'),
  Category(id: 'c11',title: 'Chocolate'),
  Category(id: 'c12',title: 'Noodles'),
  Category(id: 'c13',title: 'Tea'),
  Category(id: 'c14',title: 'Coffee'),
  Category(id: 'c15',title: 'Juice'),
  Category(id: 'c16',title: 'Chips'),
  Category(id: 'c17',title: 'Instant Mix'),
  Category(id: 'c18',title: 'Instant Food'),
  Category(id: 'c19',title: 'Ice Creams'),
  Category(id: 'c20',title: 'Jams'),
  Category(id: 'c21',title: 'Biscuits'),
  Category(id: 'c22',title: 'Soap'),
  Category(id: 'c23',title: 'Dairy Products'),
  Category(id: 'c24',title: 'Atta'),
  Category(id: 'c25',title: 'Honey'),
  Category(id: 'c26',title: 'Clothing'),
  Category(id: 'c27',title: 'Cigarette'),
  Category(id: 'c28',title: 'Salt'),
  Category(id: 'c29',title: 'Bread'),
  Category(id: 'c30',title: 'Masala'),
];