import './models/item.dart';

List<Item> ITEMS = [
      Item(company: 'DABUR',id:'c2',title: 'Toothpaste',indian: true,name:'Lal Dant Manjan',pid:'pr1',
          company_hindi: 'डाबर',title_hindi: 'टूथपेस्ट',name_hindi:'लाल दन्त मंजन'),
      Item(company: 'PATANJALI',id:'c2',title: 'Toothpaste',indian: true,name:'Dant Kanti',pid:'pr2',
          company_hindi: 'पतंजलि',title_hindi: 'टूथपेस्ट',name_hindi:'दंत कांति'),
      Item(company: 'PATANJALI',id:'c3',title: 'Shampoo',indian: true,name: 'Kesh Kanti Natural Hair Cleanser',pid:'pr3',
          company_hindi: 'पतंजलि',title_hindi: 'शैम्पू',name_hindi: 'केश कांति प्राकृतिक बाल क्लीन्ज़र'),
      Item(company: 'PATANJALI',id:'c4',title: 'Face Wash',indian: true,name:'Saundarya Face Wash',pid:'pr4',
          company_hindi: 'पतंजलि',title_hindi: 'फेस वाश',name_hindi:'सौन्दर्य फेस वाश'),
      Item(company: 'PATANJALI',id: 'c23',title: 'Dairy Products',indian: true,name:'Ghee',pid:'pr5',
          company_hindi: 'पतंजलि',title_hindi: 'डेयरी प्रोडक्ट',name_hindi:'घी'),
      Item(company: 'PATANJALI',id: 'c5',title: 'Personal Care',indian: true,name:'Saundarya Aloe vera Gel',pid:'pr6',
          company_hindi: 'पतंजलि',title_hindi: 'पर्सनल केयर',name_hindi:'सौन्दर्य एलोवेरा जेल'),
      Item(company: 'PATANJALI',id: 'c5',title: 'Personal Care',indian: true,name:'Coconut Hair Oil ',pid:'pr7',
          company_hindi: 'पतंजलि',title_hindi: 'पर्सनल केयर',name_hindi:'नारियल तेल '),
      Item(company: 'PATANJALI',id: 'c15',title: 'Juice',indian: true,name:' Amla Juice ',pid:'pr8',
          company_hindi: 'पतंजलि',title_hindi: 'जूस',name_hindi:' अमला जूस '),
      Item(company: 'PATANJALI',id: 'c25',title: 'Honey',indian: true,name:'Honey',pid:'pr9',
          company_hindi: 'पतंजलि',title_hindi: 'शहद',name_hindi:'शहद'),
      Item(company: 'ITC',id: 'c27',title: 'Cigarette',indian: true,name:'Wills cigarette',pid:'pr10',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'सिगरेट',name_hindi:'विल्स सिगरेट'),
      Item(company: 'ITC',id: 'c24',title: 'Atta',indian: true,name:'Aashirvaad atta',pid:'pr11',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'आटा',name_hindi:'आशिर्वाद आटा'),
      Item(company: 'ITC',id: 'c11',title: 'Chocolate',indian: true,name:'Candyman',pid:'pr12',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'चॉकलेट',name_hindi:'कैंडीमेन'),
      Item(company: 'ITC',id: 'c30',title: 'Masala',indian: true,name:'Aashirvaad turmeric and chilli powder',pid:'pr13',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'मसाला',name_hindi:'अशीरवाड हल्दी और मिर्च पाउडर'),
      Item(company: 'ITC',id: 'c18',title: 'Instant Food',indian: true,name:'Aashirvaad gulab jamun mix',pid:'pr14',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'इन्स्टॅन्ट फ़ूड',name_hindi:'आशिरवाद गुलाब जामुन मिक्स'),
      Item(company: 'ITC',id: 'c18',title: 'Instant Food',indian: true,name:'Kitchens of India ',pid:'pr15',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'इन्स्टॅन्ट फ़ूड',name_hindi:'Kitchens of India '),
      Item(company: 'ITC',id: 'c23',title: 'Dairy Products',indian: true,name:'Aashirvaad Svasti Ghee',pid:'pr16',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'डेयरी प्रोडक्ट',name_hindi:'आशिरवाद स्वस्ति घी'),
      Item(company: 'ITC',id: 'c21',title: 'Biscuits',indian: true,name:'Sunfeast ',pid:'pr17',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'बिस्कुट',name_hindi:'सनफीस्ट '),
      Item(company: 'ITC',id: 'c5',title: 'Personal Care',indian: true,name:'Savlon ',pid:'pr18',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'Savlon '),
      Item(company: 'ITC',id: 'c1',title: 'Soap',indian: true,name:'Fiama di wills ',pid:'pr19',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'सोप',name_hindi:'फ़ियामा दी वसीयतें '),
      Item(company: 'ITC',id: 'c26',title: 'Clothing',indian: true,name:'John players apparels',pid:'pr20',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'क्लोदिंग',name_hindi:'John players apparels'),
      Item(company: 'ITC',id: 'c5',title: 'Personal Care',indian: true,name:'Vivel ',pid:'pr21',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'Vivel '),
      Item(company: 'ITC',id: 'c12',title: 'Noodles',indian: true,name:'Yippee ',pid:'pr22',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'नूडल्स',name_hindi:'यीपी '),
      Item(company: 'ITC',id: 'c21',title: 'Biscuits',indian: true,name:'Sunfeast ',pid:'pr23',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'बिस्कुट',name_hindi:'सनफीस्ट '),
      Item(company: 'ITC',id: 'c14',title: 'Coffee',indian: true,name:'Sunbean ',pid:'pr24',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'कॉफ़ी',name_hindi:'Sunbean '),
      Item(company: 'ITC',id: 'c11',title: 'Chocolate',indian: true,name:'Fabelle  ',pid:'pr25',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'चॉकलेट',name_hindi:'Fabelle  '),
      Item(company: 'ITC',id: 'c15',title: 'Juice',indian: true,name:'B natural  ',pid:'pr26',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'जूस',name_hindi:'B natural  '),
      Item(company: 'ITC',id: 'c14',title: 'Coffee',indian: true,name:'Bingo',pid:'pr27',
          company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'कॉफ़ी',name_hindi:'बिंगो'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'KitKat',pid:'pr28',
          company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'किट कैट'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Munch',pid:'pr29',
          company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'मंच'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Munch Nuts',pid:'pr30',
          company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'मंच नट'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Milkybar Chocolate',pid:'pr31',
          company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'मिल्कीबार चॉकलेट'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Alpino',pid:'pr32',
          company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'Alpino'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'BARONE',pid:'pr33',
          company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'BARONE'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Classic',pid:'pr34',
          company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'क्लासिक'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Milkybar Eclairs',pid:'pr35',
          company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'मिल्कीबार Eclairs'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'CHOCO LICKO Éclairs',pid:'pr36',
          company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'CHOCO LICKO Éclairs'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Eclair',pid:'pr37',
          company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'Eclair'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'POLO',pid:'pr38',
          company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'पोलो'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Fox\’s Crystal Clear Fruits Flavored Candy Tin',pid:'pr39',
          company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'Fox\’s Crystal Clear Fruits Flavored Candy Tin'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'After Eight Mint Chocolate Thins',pid:'pr40',
          company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'After Eight Mint चॉकलेट Thins'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Sweet Tarts Original Candy Box',pid:'pr41',
          company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'Sweet Tarts Original Candy Box'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Quality Street Toffees Tin',pid:'pr42',
          company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'Quality Street Toffees Tin'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Rowntrees Fruit Gum',pid:'pr43',
          company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'Rowntrees Fruit Gum'),
      Item(company: 'NESTLE',id: 'c12',title: 'Noodles',indian: false,name:'MAGGIE',pid:'pr44',
          company_hindi: 'नेस्ले',title_hindi: 'नूडल्स',name_hindi:'मैगी'),
      Item(company: 'Hindustan Unilever Limited',id: 'c28',title: 'Salt',indian: false,name:'Annapurna salt ',pid:'pr45',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'साल्ट',name_hindi:'अन्नपूर्णा नमक '),
      Item(company: 'Hindustan Unilever Limited',id: 'c14',title: 'Coffee',indian: false,name:'Bru coffee ',pid:'pr46',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'कॉफ़ी',name_hindi:'ब्रू कॉफी '),
      Item(company: 'Hindustan Unilever Limited',id: 'c13',title: 'Tea',indian: false,name:'Brooke Bond tea ',pid:'pr47',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'चाय',name_hindi:'ब्रुक बॉन्ड चाय '),
      Item(company: 'Hindustan Unilever Limited',id: 'c20',title: 'Jams',indian: false,name:'Kissan jams',pid:'pr48',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'जैम',name_hindi:'किसान जेम'),
      Item(company: 'Hindustan Unilever Limited',id: 'c13',title: 'Tea',indian: false,name:'Lipton tea',pid:'pr49',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'चाय',name_hindi:'लिप्टन चाय'),
      Item(company: 'Hindustan Unilever Limited',id: 'c18',title: 'Instant Food',indian: false,name:'Knorr soups & noodles',pid:'pr50',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'इन्स्टॅन्ट फ़ूड',name_hindi:'Knorr soups & noodles'),
      Item(company: 'Hindustan Unilever Limited',id: 'c19',title: 'Ice Creams',indian: false,name:'Kwality Wall\'s frozen dessert',pid:'pr51',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'आइसक्रीम',name_hindi:'Kwality Wall\'s frozen dessert'),
      Item(company: 'Hindustan Unilever Limited',id: 'c19',title: 'Ice Creams',indian: false,name:'Magnum (ice cream)',pid:'pr52',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'आइसक्रीम',name_hindi:'मैग्नम (आइसक्रीम)'),
      Item(company: 'Hindustan Unilever Limited',id: 'c29',title: 'Bread',indian: false,name:'Modern Bread',pid:'pr53',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'ब्रेड',name_hindi:'Modern ब्रेड'),
      Item(company: 'Hindustan Unilever Limited',id: 'c24',title: 'Atta',indian: false,name:'Annapurna atta',pid:'pr54',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'आटा',name_hindi:'Annapurna atta'),
      Item(company: 'Hindustan Unilever Limited',id: 'c12',title: 'Noodles',indian: false,name:'Knorr  noodles',pid:'pr55',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'नूडल्स',name_hindi:'नॉर नूडल्स'),
      Item(company: 'Hindustan Unilever Limited',id: 'c7',title: 'Detergent',indian: false,name:'Active Wheel detergent',pid:'pr56',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'डिटर्जेंट',name_hindi:'Active Wheel detergent'),
      Item(company: 'Hindustan Unilever Limited',id: 'c7',title: 'Detergent',indian: false,name:'Comfort fabric softeners',pid:'pr57',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'डिटर्जेंट',name_hindi:'Comfort fabric softeners'),
      Item(company: 'Hindustan Unilever Limited',id: 'c7',title: 'Detergent',indian: false,name:'Rin detergents and bleach',pid:'pr58',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'डिटर्जेंट',name_hindi:'Rin detergents and bleach'),
      Item(company: 'Hindustan Unilever Limited',id: 'c7',title: 'Detergent',indian: false,name:'Sunlight detergent and colour care',pid:'pr59',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'डिटर्जेंट',name_hindi:'Sunlight detergent and colour care'),
      Item(company: 'Hindustan Unilever Limited',id: 'c7',title: 'Detergent',indian: false,name:'Surf Excel detergent and gentle wash',pid:'pr60',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'डिटर्जेंट',name_hindi:'सर्फ एक्सेल डिटर्जेंट और gentle wash'),
      Item(company: 'Hindustan Unilever Limited',id: 'c5',title: 'Personal Care',indian: false,name:'Axe deodorant',pid:'pr61',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'Axe deodorant'),
      Item(company: 'Hindustan Unilever Limited',id: 'c5',title: 'Personal Care',indian: false,name:'LEVER Ayush Therapy ayurvedic health care and personal care',pid:'pr62',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'LEVER Ayush Therapy ayurvedic health care and personal care'),
      Item(company: 'Hindustan Unilever Limited',id: 'c5',title: 'Personal Care',indian: false,name:'Dove',pid:'pr63',
        company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'डव',),
      Item(company: 'Hindustan Unilever Limited',id: 'c5',title: 'Personal Care',indian: false,name:'Fair & Lovely',pid:'pr64',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'फेयर एंड लवली'),
      Item(company: 'Hindustan Unilever Limited',id: 'c5',title: 'Personal Care',indian: false,name:'Lakmé',pid:'pr65',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'लक्मे'),
      Item(company: 'Hindustan Unilever Limited',id: 'c5',title: 'Personal Care',indian: false,name:'Vaseline petroleum jelly, skin care lotions',pid:'pr66',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'Vaseline petroleum jelly, skin care lotions'),
      Item(company: 'Hindustan Unilever Limited',id: 'c1',title: 'Soap',indian: false,name:'Breeze beauty soap',pid:'pr67',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'सोप',name_hindi:'ब्रीज़ ब्यूटी साबुन'),
      Item(company: 'Hindustan Unilever Limited',id: 'c1',title: 'Soap',indian: false,name:'Lifebuoy',pid:'pr68',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'सोप',name_hindi:'लाइफबॉय'),
      Item(company: 'Hindustan Unilever Limited',id: 'c1',title: 'Soap',indian: false,name:'Liril',pid:'pr69',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'सोप',name_hindi:'लिरिल'),
      Item(company: 'Hindustan Unilever Limited',id: 'c1',title: 'Soap',indian: false,name:'Lux',pid:'pr70',
        company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'सोप',name_hindi:'Lux',),
      Item(company: 'Hindustan Unilever Limited',id: 'c1',title: 'Soap',indian: false,name:'Pears',pid:'pr71',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'सोप',name_hindi:'पियर्स'),
      Item(company: 'Hindustan Unilever Limited',id: 'c1',title: 'Soap',indian: false,name:'Rexona soap',pid:'pr72',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'सोप',name_hindi:'रेक्सोना सोप'),
      Item(company: 'Hindustan Unilever Limited',id: 'c3',title: 'Shampoo',indian: false,name:'Sunsilk shampoo',pid:'pr73',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'शैम्पू',name_hindi:'सनसिल्क शैम्पू'),
      Item(company: 'Hindustan Unilever Limited',id: 'c3',title: 'Shampoo',indian: false,name:'TRESemmé',pid:'pr74',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'शैम्पू',name_hindi:'TRESemmé'),
      Item(company: 'Hindustan Unilever Limited',id: 'c3',title: 'Shampoo',indian: false,name:'Clinic Plus shampoo ',pid:'pr75',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'शैम्पू',name_hindi:'क्लिनिक प्लस शैम्पू '),
      Item(company: 'Hindustan Unilever Limited',id: 'c2',title: 'Toothpaste',indian: false,name:'Close Up toothpaste',pid:'pr76',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'टूथपेस्ट',name_hindi:'क्लोज़ अप टूथपेस्ट'),
      Item(company: 'Hindustan Unilever Limited',id: 'c2',title: 'Toothpaste',indian: false,name:'Pepsodent toothpaste',pid:'pr77',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'टूथपेस्ट',name_hindi:'पेप्सोडेंट टूथपेस्ट'),
      Item(company: 'Hindustan Unilever Limited',id: 'c8',title: 'Shaving ',indian: false,name:'Denim',pid:'pr78',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'शेविंग ',name_hindi:'डेनिम'),
      Item(company: 'Hindustan Unilever Limited',id: 'c5',title: 'Personal Care',indian: false,name:'Pond\'s talcs ',pid:'pr79',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'Pond\'s talcs '),
      Item(company: 'Hindustan Unilever Limited',id: 'c2',title: 'Toothpaste',indian: false,name:'Pepsodent toothpaste',pid:'pr80',
          company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'टूथपेस्ट',name_hindi:'पेप्सोडेंट टूथपेस्ट'),
    ];

    List<Item> ITEMS_HINDI = [
      Item(company_hindi: 'डाबर',title_hindi: 'टूथपेस्ट',name_hindi:'लाल दन्त मंजन'),
      Item(company_hindi: 'पतंजलि',title_hindi: 'टूथपेस्ट',name_hindi:'दंत कांति'),
      Item(company_hindi: 'पतंजलि',title_hindi: 'शैम्पू',name_hindi: 'केश कांति प्राकृतिक बाल क्लीन्ज़र'),
      Item(company_hindi: 'पतंजलि',title_hindi: 'फेस वाश',name_hindi:'सौन्दर्य फेस वाश'),
      Item(company_hindi: 'पतंजलि',title_hindi: 'डेयरी प्रोडक्ट',name_hindi:'घी'),
      Item(company_hindi: 'पतंजलि',title_hindi: 'पर्सनल केयर',name:'सौन्दर्य एलोवेरा जेल'),
      Item(company_hindi: 'पतंजलि',title_hindi: 'पर्सनल केयर',name:'नारियल तेल '),
      Item(company_hindi: 'पतंजलि',title_hindi: 'जूस',name:' अमला जूस '),
      Item(company_hindi: 'पतंजलि',title_hindi: 'शहद',name:'शहद'),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'सिगरेट',name_hindi:'विल्स सिगरेट'),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'आटा',name_hindi:'आशिर्वाद आटा'),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'चॉकलेट',name_hindi:'कैंडीमेन'),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'मसाला',name_hindi:'अशीरवाड हल्दी और मिर्च पाउडर'),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'इन्स्टॅन्ट फ़ूड',name_hindi:'आशिरवाद गुलाब जामुन मिक्स'),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'इन्स्टॅन्ट फ़ूड',name_hindi:'Kitchens of India '),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'डेयरी प्रोडक्ट',name_hindi:'आशिरवाद स्वस्ति घी'),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'बिस्कुट',name_hindi:'सनफीस्ट '),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'Savlon '),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'सोप',name_hindi:'फ़ियामा दी वसीयतें '),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'क्लोदिंग',name_hindi:'John players apparels'),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'Vivel '),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'नूडल्स',name_hindi:'यीपी '),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'बिस्कुट',name_hindi:'सनफीस्ट '),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'कॉफ़ी',name_hindi:'Sunbean '),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'चॉकलेट',name_hindi:'Fabelle  '),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'जूस',name_hindi:'B natural  '),
      Item(company_hindi: 'इंडियन टोबैको कंपनी लिमिटेड',title_hindi: 'कॉफ़ी',name_hindi:'बिंगो'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'किट कैट'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'मंच'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'मंच नट'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'मिल्कीबार चॉकलेट'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'Alpino'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'BARONE'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'क्लासिक'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'मिल्कीबार Eclairs'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'CHOCO LICKO Éclairs'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'Eclair'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'पोलो'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'Fox\’s Crystal Clear Fruits Flavored Candy Tin'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'After Eight Mint चॉकलेट Thins'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'Sweet Tarts Original Candy Box'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'Quality Street Toffees Tin'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'चॉकलेट',name_hindi:'Rowntrees Fruit Gum'),
      Item(company_hindi: 'नेस्ले',title_hindi: 'नूडल्स',name_hindi:'मैगी'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'साल्ट',name_hindi:'अन्नपूर्णा नमक '),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'कॉफ़ी',name_hindi:'ब्रू कॉफी '),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'चाय',name_hindi:'ब्रुक बॉन्ड चाय '),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'जैम',name_hindi:'किसान जेम'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'चाय',name_hindi:'लिप्टन चाय'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'इन्स्टॅन्ट फ़ूड',name_hindi:'Knorr soups & noodles'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'आइसक्रीम',name_hindi:'Kwality Wall\'s frozen dessert'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'आइसक्रीम',name_hindi:'मैग्नम (आइसक्रीम)'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'ब्रेड',name_hindi:'Modern ब्रेड'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'आटा',name_hindi:'Annapurna atta'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'नूडल्स',name_hindi:'नॉर नूडल्स'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'डिटर्जेंट',name_hindi:'Active Wheel detergent'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'डिटर्जेंट',name_hindi:'Comfort fabric softeners'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'डिटर्जेंट',name_hindi:'Rin detergents and bleach'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'डिटर्जेंट',name_hindi:'Sunlight detergent and colour care'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'डिटर्जेंट',name_hindi:'सर्फ एक्सेल डिटर्जेंट और gentle wash'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'Axe deodorant'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'LEVER Ayush Therapy ayurvedic health care and personal care'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'डव',),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'फेयर एंड लवली'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'लक्मे'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'Vaseline petroleum jelly, skin care lotions'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'सोप',name_hindi:'ब्रीज़ ब्यूटी साबुन'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'सोप',name_hindi:'लाइफबॉय'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'सोप',name_hindi:'लिरिल'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'सोप',name_hindi:'Lux',),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'सोप',name_hindi:'पियर्स'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'सोप',name_hindi:'रेक्सोना साबुन'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'शैम्पू',name_hindi:'सनसिल्क शैम्पू'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'शैम्पू',name_hindi:'TRESemmé'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'शैम्पू',name_hindi:'क्लिनिक प्लस शैम्पू '),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'टूथपेस्ट',name_hindi:'क्लोज़ अप टूथपेस्ट'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'टूथपेस्ट',name_hindi:'पेप्सोडेंट टूथपेस्ट'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'शेविंग ',name_hindi:'डेनिम'),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'पर्सनल केयर',name_hindi:'Pond\'s talcs '),
      Item(company_hindi: 'हिंदुस्तान युनिलिवर लिमिटेड',title_hindi: 'टूथपेस्ट',name_hindi:'पेप्सोडेंट टूथपेस्ट'),
    ];
  