import './models/item.dart';

List<Item> ITEMS = [
      Item(company: 'DABUR',id:'c2',title: 'Toothpaste',indian: true,name:'Lal Dant Manjan',pid:'pr1'),
      Item(company: 'PATANJALI',id:'c2',title: 'Toothpaste',indian: true,name:'Dant Kanti',pid:'pr2'),
      Item(company: 'PATANJALI',id:'c3',title: 'Shampoo',indian: true,name: 'Kesh Kanti Natural Hair Cleanser',pid:'pr3'),
      Item(company: 'PATANJALI',id:'c4',title: 'Face Wash',indian: true,name:'Saundarya Face Wash',pid:'pr4'),
      Item(company: 'PATANJALI',id: 'c23',title: 'Dairy Products',indian: true,name:'Ghee',pid:'pr5'),
      Item(company: 'PATANJALI',id: 'c5',title: 'Personal Care',indian: true,name:'Saundarya Aloe vera Gel',pid:'pr6'),
      Item(company: 'PATANJALI',id: 'c5',title: 'Personal Care',indian: true,name:'Coconut Hair Oil ',pid:'pr7'),
      Item(company: 'PATANJALI',id: 'c15',title: 'Juice',indian: true,name:' Amla Juice ',pid:'pr8'),
      Item(company: 'PATANJALI',id: 'c25',title: 'Honey',indian: true,name:'Honey',pid:'pr9'),
      Item(company: 'ITC',id: 'c27',title: 'Cigarette',indian: true,name:'Wills cigarette',pid:'pr10'),
      Item(company: 'ITC',id: 'c24',title: 'Atta',indian: true,name:'Aashirvaad atta',pid:'pr11'),
      Item(company: 'ITC',id: 'c11',title: 'Chocolate',indian: true,name:'Candyman',pid:'pr12'),
      Item(company: 'ITC',id: 'c30',title: 'Masala',indian: true,name:'Aashirvaad turmeric and chilli powder',pid:'pr13'),
      Item(company: 'ITC',id: 'c18',title: 'Instant Food',indian: true,name:'Aashirvaad gulab jamun mix',pid:'pr14'),
      Item(company: 'ITC',id: 'c18',title: 'Instant Food',indian: true,name:'Kitchens of India ',pid:'pr15'),
      Item(company: 'ITC',id: 'c23',title: 'Dairy Products',indian: true,name:'Aashirvaad Svasti Ghee',pid:'pr16'),
      Item(company: 'ITC',id: 'c21',title: 'Biscuits',indian: true,name:'Sunfeast ',pid:'pr17'),
      Item(company: 'ITC',id: 'c5',title: 'Personal Care',indian: true,name:'Savlon ',pid:'pr18'),
      Item(company: 'ITC',id: 'c1',title: 'Soap',indian: true,name:'Fiama di wills ',pid:'pr19'),
      Item(company: 'ITC',id: 'c26',title: 'Clothing',indian: true,name:'John players apparels',pid:'pr20'),
      Item(company: 'ITC',id: 'c5',title: 'Personal Care',indian: true,name:'Vivel ',pid:'pr21'),
      Item(company: 'ITC',id: 'c12',title: 'Noodles',indian: true,name:'Yippee ',pid:'pr22'),
      Item(company: 'ITC',id: 'c21',title: 'Biscuits',indian: true,name:'Sunfeast ',pid:'pr23'),
      Item(company: 'ITC',id: 'c14',title: 'Coffee',indian: true,name:'Sunbean ',pid:'pr24'),
      Item(company: 'ITC',id: 'c11',title: 'Chocolate',indian: true,name:'Fabelle  ',pid:'pr25'),
      Item(company: 'ITC',id: 'c15',title: 'Juice',indian: true,name:'B natural  ',pid:'pr26'),
      Item(company: 'ITC',id: 'c14',title: 'Coffee',indian: true,name:'Bingo',pid:'pr27'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'KitKat',pid:'pr28'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Munch',pid:'pr29'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Munch Nuts',pid:'pr30'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Milkybar Chocolate',pid:'pr31'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Alpino',pid:'pr32'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'BARONE',pid:'pr33'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Classic',pid:'pr34'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Milkybar Eclairs',pid:'pr35'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'CHOCO LICKO Éclairs',pid:'pr36'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Eclair',pid:'pr37'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'POLO',pid:'pr38'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Fox\’s Crystal Clear Fruits Flavored Candy Tin',pid:'pr39'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'After Eight Mint Chocolate Thins',pid:'pr40'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Sweet Tarts Original Candy Box',pid:'pr41'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Quality Street Toffees Tin',pid:'pr42'),
      Item(company: 'NESTLE',id: 'c11',title: 'Chocolate',indian: false,name:'Rowntrees Fruit Gum',pid:'pr43'),
      Item(company: 'NESTLE',id: 'c12',title: 'Noodles',indian: false,name:'MAGGIE',pid:'pr44'),
      Item(company: 'Hindustan Unilever Limited',id: 'c28',title: 'Salt',indian: false,name:'Annapurna salt ',pid:'pr45'),
      Item(company: 'Hindustan Unilever Limited',id: 'c14',title: 'Coffee',indian: false,name:'Bru coffee ',pid:'pr46'),
      Item(company: 'Hindustan Unilever Limited',id: 'c13',title: 'Tea',indian: false,name:'Brooke Bond tea ',pid:'pr47'),
      Item(company: 'Hindustan Unilever Limited',id: 'c20',title: 'Jams',indian: false,name:'Kissan jams',pid:'pr48'),
      Item(company: 'Hindustan Unilever Limited',id: 'c13',title: 'Tea',indian: false,name:'Lipton tea',pid:'pr49'),
      Item(company: 'Hindustan Unilever Limited',id: 'c18',title: 'Instant Food',indian: false,name:'Knorr soups & noodles',pid:'pr50'),
      Item(company: 'Hindustan Unilever Limited',id: 'c19',title: 'Ice Creams',indian: false,name:'Kwality Wall\'s frozen dessert',pid:'pr51'),
      Item(company: 'Hindustan Unilever Limited',id: 'c19',title: 'Ice Creams',indian: false,name:'Magnum (ice cream)',pid:'pr52'),
      Item(company: 'Hindustan Unilever Limited',id: 'c29',title: 'Bread',indian: false,name:'Modern Bread',pid:'pr53'),
      Item(company: 'Hindustan Unilever Limited',id: 'c24',title: 'Atta',indian: false,name:'Annapurna atta',pid:'pr54'),
      Item(company: 'Hindustan Unilever Limited',id: 'c12',title: 'Noodles',indian: false,name:'Knorr  noodles',pid:'pr55'),
      Item(company: 'Hindustan Unilever Limited',id: 'c7',title: 'Detergent',indian: false,name:'Active Wheel detergent',pid:'pr56'),
      Item(company: 'Hindustan Unilever Limited',id: 'c7',title: 'Detergent',indian: false,name:'Comfort fabric softeners',pid:'pr57'),
      Item(company: 'Hindustan Unilever Limited',id: 'c7',title: 'Detergent',indian: false,name:'Rin detergents and bleach',pid:'pr58'),
      Item(company: 'Hindustan Unilever Limited',id: 'c7',title: 'Detergent',indian: false,name:'Sunlight detergent and colour care',pid:'pr59'),
      Item(company: 'Hindustan Unilever Limited',id: 'c7',title: 'Detergent',indian: false,name:'Surf Excel detergent and gentle wash',pid:'pr60'),
      Item(company: 'Hindustan Unilever Limited',id: 'c5',title: 'Personal Care',indian: false,name:'Axe deodorant',pid:'pr61'),
      Item(company: 'Hindustan Unilever Limited',id: 'c5',title: 'Personal Care',indian: false,name:'LEVER Ayush Therapy ayurvedic health care and personal care',pid:'pr62'),
      Item(company: 'Hindustan Unilever Limited',id: 'c5',title: 'Personal Care',indian: false,name:'Dove',pid:'pr63'),
      Item(company: 'Hindustan Unilever Limited',id: 'c5',title: 'Personal Care',indian: false,name:'Fair & Lovely',pid:'pr64'),
      Item(company: 'Hindustan Unilever Limited',id: 'c5',title: 'Personal Care',indian: false,name:'Lakmé',pid:'pr65'),
      Item(company: 'Hindustan Unilever Limited',id: 'c5',title: 'Personal Care',indian: false,name:'Vaseline petroleum jelly, skin care lotions',pid:'pr66'),
      Item(company: 'Hindustan Unilever Limited',id: 'c1',title: 'Soap',indian: false,name:'Breeze beauty soap',pid:'pr67'),
      Item(company: 'Hindustan Unilever Limited',id: 'c1',title: 'Soap',indian: false,name:'Lifebuoy',pid:'pr68'),
      Item(company: 'Hindustan Unilever Limited',id: 'c1',title: 'Soap',indian: false,name:'Liril',pid:'pr69'),
      Item(company: 'Hindustan Unilever Limited',id: 'c1',title: 'Soap',indian: false,name:'Lux',pid:'pr70'),
      Item(company: 'Hindustan Unilever Limited',id: 'c1',title: 'Soap',indian: false,name:'Pears',pid:'pr71'),
      Item(company: 'Hindustan Unilever Limited',id: 'c1',title: 'Soap',indian: false,name:'Rexona soap',pid:'pr72'),
      Item(company: 'Hindustan Unilever Limited',id: 'c3',title: 'Shampoo',indian: false,name:'Sunsilk shampoo',pid:'pr73'),
      Item(company: 'Hindustan Unilever Limited',id: 'c3',title: 'Shampoo',indian: false,name:'TRESemmé',pid:'pr74'),
      Item(company: 'Hindustan Unilever Limited',id: 'c3',title: 'Shampoo',indian: false,name:'Clinic Plus shampoo ',pid:'pr75'),
      Item(company: 'Hindustan Unilever Limited',id: 'c2',title: 'Toothpaste',indian: false,name:'Close Up toothpaste',pid:'pr76'),
      Item(company: 'Hindustan Unilever Limited',id: 'c2',title: 'Toothpaste',indian: false,name:'Pepsodent toothpaste',pid:'pr77'),
      Item(company: 'Hindustan Unilever Limited',id: 'c8',title: 'Shaving ',indian: false,name:'Denim',pid:'pr78'),
      Item(company: 'Hindustan Unilever Limited',id: 'c5',title: 'Personal Care',indian: false,name:'Pond\'s talcs ',pid:'pr79'),
      Item(company: 'Hindustan Unilever Limited',id: 'c2',title: 'Toothpaste',indian: false,name:'Pepsodent toothpaste',pid:'pr80'),
    ];

    List<Item> ITEMS_HINDI = [
      Item(company: 'डाबर',id:'c2',title: 'टूथपेस्ट',indian: true,name:'Lal Dant Manjan',pid:'pr1'),
      Item(company: 'पतंजलि',id:'c2',title: 'टूथपेस्ट',indian: true,name:'Dant Kanti',pid:'pr2'),
      Item(company: 'पतंजलि',id:'c3',title: 'शैम्पू',indian: true,name: 'Kesh Kanti Natural Hair Cleanser',pid:'pr3'),
      Item(company: 'पतंजलि',id:'c4',title: 'फेस वाश',indian: true,name:'Saundarya फेस वाश',pid:'pr4'),
      Item(company: 'पतंजलि',id: 'c23',title: 'डेयरी प्रोडक्ट',indian: true,name:'Ghee',pid:'pr5'),
      Item(company: 'पतंजलि',id: 'c5',title: 'पर्सनल केयर',indian: true,name:'Saundarya Aloe vera Gel',pid:'pr6'),
      Item(company: 'पतंजलि',id: 'c5',title: 'पर्सनल केयर',indian: true,name:'Coconut Hair Oil ',pid:'pr7'),
      Item(company: 'पतंजलि',id: 'c15',title: 'जूस',indian: true,name:' Amla जूस ',pid:'pr8'),
      Item(company: 'पतंजलि',id: 'c25',title: 'शहद',indian: true,name:'Honey',pid:'pr9'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c27',title: 'सिगरेट',indian: true,name:'Wills cigarette',pid:'pr10'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c24',title: 'आटा',indian: true,name:'Aashirvaad atta',pid:'pr11'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c11',title: 'चॉकलेट',indian: true,name:'Candyman',pid:'pr12'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c30',title: 'मसाला',indian: true,name:'Aashirvaad turmeric and chilli powder',pid:'pr13'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c18',title: 'इन्स्टॅन्ट फ़ूड',indian: true,name:'Aashirvaad gulab jamun mix',pid:'pr14'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c18',title: 'इन्स्टॅन्ट फ़ूड',indian: true,name:'Kitchens of India ',pid:'pr15'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c23',title: 'डेयरी प्रोडक्ट',indian: true,name:'Aashirvaad Svasti Ghee',pid:'pr16'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c21',title: 'बिस्कुट',indian: true,name:'Sunfeast ',pid:'pr17'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c5',title: 'पर्सनल केयर',indian: true,name:'Savlon ',pid:'pr18'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c1',title: 'सोप',indian: true,name:'Fiama di wills ',pid:'pr19'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c26',title: 'क्लोदिंग',indian: true,name:'John players apparels',pid:'pr20'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c5',title: 'पर्सनल केयर',indian: true,name:'Vivel ',pid:'pr21'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c12',title: 'नूडल्स',indian: true,name:'Yippee ',pid:'pr22'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c21',title: 'बिस्कुट',indian: true,name:'Sunfeast ',pid:'pr23'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c14',title: 'कॉफ़ी',indian: true,name:'Sunbean ',pid:'pr24'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c11',title: 'चॉकलेट',indian: true,name:'Fabelle  ',pid:'pr25'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c15',title: 'जूस',indian: true,name:'B natural  ',pid:'pr26'),
      Item(company: 'इंडियन टोबैको कंपनी लिमिटेड',id: 'c14',title: 'कॉफ़ी',indian: true,name:'Bingo',pid:'pr27'),
      Item(company: 'नेस्ले',id: 'c11',title: 'चॉकलेट',indian: false,name:'KitKat',pid:'pr28'),
      Item(company: 'नेस्ले',id: 'c11',title: 'चॉकलेट',indian: false,name:'Munch',pid:'pr29'),
      Item(company: 'नेस्ले',id: 'c11',title: 'चॉकलेट',indian: false,name:'Munch Nuts',pid:'pr30'),
      Item(company: 'नेस्ले',id: 'c11',title: 'चॉकलेट',indian: false,name:'Milkybar चॉकलेट',pid:'pr31'),
      Item(company: 'नेस्ले',id: 'c11',title: 'चॉकलेट',indian: false,name:'Alpino',pid:'pr32'),
      Item(company: 'नेस्ले',id: 'c11',title: 'चॉकलेट',indian: false,name:'BARONE',pid:'pr33'),
      Item(company: 'नेस्ले',id: 'c11',title: 'चॉकलेट',indian: false,name:'Classic',pid:'pr34'),
      Item(company: 'नेस्ले',id: 'c11',title: 'चॉकलेट',indian: false,name:'Milkybar Eclairs',pid:'pr35'),
      Item(company: 'नेस्ले',id: 'c11',title: 'चॉकलेट',indian: false,name:'CHOCO LICKO Éclairs',pid:'pr36'),
      Item(company: 'नेस्ले',id: 'c11',title: 'चॉकलेट',indian: false,name:'Eclair',pid:'pr37'),
      Item(company: 'नेस्ले',id: 'c11',title: 'चॉकलेट',indian: false,name:'POLO',pid:'pr38'),
      Item(company: 'नेस्ले',id: 'c11',title: 'चॉकलेट',indian: false,name:'Fox\’s Crystal Clear Fruits Flavored Candy Tin',pid:'pr39'),
      Item(company: 'नेस्ले',id: 'c11',title: 'चॉकलेट',indian: false,name:'After Eight Mint चॉकलेट Thins',pid:'pr40'),
      Item(company: 'नेस्ले',id: 'c11',title: 'चॉकलेट',indian: false,name:'Sweet Tarts Original Candy Box',pid:'pr41'),
      Item(company: 'नेस्ले',id: 'c11',title: 'चॉकलेट',indian: false,name:'Quality Street Toffees Tin',pid:'pr42'),
      Item(company: 'नेस्ले',id: 'c11',title: 'चॉकलेट',indian: false,name:'Rowntrees Fruit Gum',pid:'pr43'),
      Item(company: 'नेस्ले',id: 'c12',title: 'नूडल्स',indian: false,name:'MAGGIE',pid:'pr44'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c28',title: 'साल्ट',indian: false,name:'Annapurna salt ',pid:'pr45'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c14',title: 'कॉफ़ी',indian: false,name:'Bru coffee ',pid:'pr46'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c13',title: 'चाय',indian: false,name:'Brooke Bond tea ',pid:'pr47'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c20',title: 'जैम',indian: false,name:'Kissan jams',pid:'pr48'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c13',title: 'चाय',indian: false,name:'Lipton tea',pid:'pr49'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c18',title: 'इन्स्टॅन्ट फ़ूड',indian: false,name:'Knorr soups & noodles',pid:'pr50'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c19',title: 'आइसक्रीम',indian: false,name:'Kwality Wall\'s frozen dessert',pid:'pr51'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c19',title: 'आइसक्रीम',indian: false,name:'Magnum (ice cream)',pid:'pr52'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c29',title: 'ब्रेड',indian: false,name:'Modern ब्रेड',pid:'pr53'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c24',title: 'आटा',indian: false,name:'Annapurna atta',pid:'pr54'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c12',title: 'नूडल्स',indian: false,name:'Knorr  noodles',pid:'pr55'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c7',title: 'डिटर्जेंट',indian: false,name:'Active Wheel detergent',pid:'pr56'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c7',title: 'डिटर्जेंट',indian: false,name:'Comfort fabric softeners',pid:'pr57'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c7',title: 'डिटर्जेंट',indian: false,name:'Rin detergents and bleach',pid:'pr58'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c7',title: 'डिटर्जेंट',indian: false,name:'Sunlight detergent and colour care',pid:'pr59'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c7',title: 'डिटर्जेंट',indian: false,name:'Surf Excel detergent and gentle wash',pid:'pr60'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c5',title: 'पर्सनल केयर',indian: false,name:'Axe deodorant',pid:'pr61'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c5',title: 'पर्सनल केयर',indian: false,name:'LEVER Ayush Therapy ayurvedic health care and personal care',pid:'pr62'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c5',title: 'पर्सनल केयर',indian: false,name:'Dove',pid:'pr63'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c5',title: 'पर्सनल केयर',indian: false,name:'Fair & Lovely',pid:'pr64'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c5',title: 'पर्सनल केयर',indian: false,name:'Lakmé',pid:'pr65'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c5',title: 'पर्सनल केयर',indian: false,name:'Vaseline petroleum jelly, skin care lotions',pid:'pr66'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c1',title: 'सोप',indian: false,name:'Breeze beauty soap',pid:'pr67'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c1',title: 'सोप',indian: false,name:'Lifebuoy',pid:'pr68'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c1',title: 'सोप',indian: false,name:'Liril',pid:'pr69'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c1',title: 'सोप',indian: false,name:'Lux',pid:'pr70'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c1',title: 'सोप',indian: false,name:'Pears',pid:'pr71'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c1',title: 'सोप',indian: false,name:'Rexona soap',pid:'pr72'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c3',title: 'शैम्पू',indian: false,name:'Sunsilk shampoo',pid:'pr73'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c3',title: 'शैम्पू',indian: false,name:'TRESemmé',pid:'pr74'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c3',title: 'शैम्पू',indian: false,name:'Clinic Plus shampoo ',pid:'pr75'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c2',title: 'टूथपेस्ट',indian: false,name:'Close Up Toothpaste',pid:'pr76'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c2',title: 'टूथपेस्ट',indian: false,name:'Pepsodent Toothpaste',pid:'pr77'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c8',title: 'शेविंग ',indian: false,name:'Denim',pid:'pr78'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c5',title: 'पर्सनल केयर',indian: false,name:'Pond\'s talcs ',pid:'pr79'),
      Item(company: 'हिंदुस्तान युनिलिवर लिमिटेड',id: 'c2',title: 'टूथपेस्ट',indian: false,name:'Pepsodent Toothpaste',pid:'pr80'),

    ];
  